concurrency4a: Concurrency4a.c
	gcc Concurrency4a.c -o concurrency4a -lpthread


concurrency4b: Concurrency4b.c
	gcc Concurrency4b.c -o concurrency4b -lpthread


clean:
	rm concurrency4a concurrency4b
