Concurrency4a: Concurrency4a.c
	gcc Concurrency4a.c -o Concurrency4a -lpthread
Concurrency4b: Concurrency4b.c
	gcc Concurrency4b.c -o Concurrency4b -lpthread

clean:
	rm Concurrency4a
	rm Concurrency4b
